### ISSUE TITLE
[feature] This panel makes it seem as if I'm transfering the wallet balance

### ISSUE THREAD

**Issue by helpfulBro** [ETHLend/Baiji-public#16]
I think it needs to be made clear that the top panel is the current balance. Today it looks like the total wallet balance will be sent.

![image](https://user-images.githubusercontent.com/25915621/48878081-aa328780-ee51-11e8-8c33-f95244a23b81.png)

Perhaps something like this?

![image](https://user-images.githubusercontent.com/25915621/48878282-87ed3980-ee52-11e8-97c5-a2d4509ff004.png)

**Comment by The-3D** [comment]
Nice finding, you are right. The header should ideally show the idea of the transfer, so we will replace the actual balance with  the transaction amount, and find another place to show the balance.

**Comment by jp8219** [comment]
The wallet balance did make it seem that was what I was pledging instead of my wallet balance. Maybe make it more clear on the header that "this is your wallet balance" and another box that displays "this is what is being lent or borrowed". As it is now if it were my real money I would have not proceeded with the process because it isn't clear.

**Comment by helpfulBrother** [comment]
@jp8219 this is exactly what I did, ended up backing out of the transaction because it's not clear what is happening.
