### ISSUE TITLE
[bug] Able to borrow without required collateral

### ISSUE THREAD

**Issue by helpfulBrother** [ETHLend/Baiji-public#55]
I have less than 3 ETH in my wallet, but am able to click take this loan and progress.

![image](https://user-images.githubusercontent.com/44999712/50634639-21078800-0f9b-11e9-8506-22c8048a75e7.png)

Also stuck on Validating Offer with same out of gas error as previous bug https://kovan.etherscan.io/address/0xF08087dF865f86A0A285C9c71BE78A8135091aae

**Comment by The-3D** [comment]
This is expected behavior, as it's simpler for the user, in terms of implementation and for compatibility, in the future, with external wallets. What is missing here is that the approve transaction dialog should recognize the balance and show the "insufficient funds" message (same behavior as metamask) which is related with issue #35. One of the few things that remaining to be implemented before the release

**Comment by The-3D** [comment]
if you try to send the transaction btw it will fail so it's an UI improvement that needs to be completed.

**Comment by The-3D** [comment]
i stand incorrect on this. I tried to replicate the error and i actually managed to get a loan without having the actual funds in the wallet. This happens only in the case of ETH as a collateral. This is a critical bug that will be addressed accordingly @sirsoth. Thanks
